name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn nx dep-graph --file=dist/gh-pages/output.html

      - name: Deploy
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: 'dist/gh-pages/'
        uses: maxheld83/ghpages@v0.3.0
